---
- name: Create VLAN Interfaces
  netbox.netbox.netbox_device_interface:
    netbox_url: http://192.168.174.157:8000
    netbox_token: 0123456789abcdef0123456789abcdef01234567
    data: "{{ interface }}"
    state: present    
  loop: "{{ interfaces }}"
  loop_control: 
    loop_var: interface
    label: "{{ interface['name']}}"
