---
- name: Assign IP Addresses to interfaces
  netbox.netbox.netbox_ip_address:
#    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
    netbox_url:  http://192.168.174.157:8000/
    netbox_token: 0123456789abcdef0123456789abcdef01234567
#    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
    data: "{{ ip }}"  
    state: present
  loop: "{{ ip_addresses }}"
  loop_control: 
    loop_var: ip
    label: "{{ ip['assigned_object']}}"
